service: hono-deploy-demo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: development
    CORS_ORIGIN: '*'
    RATE_LIMIT_WINDOW: '900000'
    RATE_LIMIT_MAX: '100'
    LOG_LEVEL: 'info'

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - aws-sdk
    target: node20
    platform: node
    format: cjs
    concurrency: 10
    packagePath: lambda-package.json